[package]
name = "Cowcord"
version = "0.0.1"
edition = "2024"

[dependencies]

# core deps
dioxus = { version = "0.6.3", features = ["router"] }
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = [
    "Window",
    "Element",
    "DomRect",
    "WebSocket",
    "MessageEvent",
    "BinaryType",
    "ErrorEvent",
    "CloseEvent",
    "console",
] }

# feature deps
gloo-timers = "0.3.0"
reqwest = { version = "0.12.15", features = ["json", "blocking", "multipart"] }

[features]
default = ["dekstop"]
desktop = ["dioxus/desktop"]
