[package]
name = "update-error-codes"
version = "0.0.1"
edition = "2024"

[dependencies]
reqwest = "0.12.23"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
