#!/usr/bin/env bash
set -euo pipefail

file="$(dirname $(dirname $(dirname $(dirname "$BASH_SOURCE[0]"))))/crates/discord-types/src/common/error_codes.rs"

mkdir -p "$(dirname "$file")"

json=$(curl -s "https://docs.discord.food/api/codes")

cat > "$file" <<'EOF'
//! Autogenerated file via `scripts/update-error-codes`

use phf::phf_map;

static ERROR_CODES: phf::Map<u32, &'static str> = phf_map! {
EOF

echo "$json" | jq -r '
  .[] | .codes | to_entries[] | "\t\(.key)u32 => \"\(.value)\","
' >> "$file"

cat >> "$file" <<'EOF'
};

trait ErrorCode {
	fn get_error_group(&self) -> &str;
}

impl ErrorCode for u32 {
	fn get_error_group(&self) -> &str {
		return match self / 10_000 {
EOF

echo "$json" | jq -r '
  .[] | "\t\t\t| \(.index) => \"\(.name)\","
' >> "$file"

cat >> "$file" <<'EOF'
			| _ => "Unknown group",
		};
	}
}
EOF
