name: Deploy Beta

on:
  push:
    branches:
      - beta

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip_deploy')"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.os == 'ubuntu-latest' && 'wasm32-unknown-unknown' || '' }}

      - uses: Swatinem/rust-cache@v2

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli
        env:
          RUSTFLAGS: ${{ matrix.os == 'windows-latest' && '-C link-arg=/LIBPATH:"C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64" -C link-arg=advapi32.lib -C link-arg=crypt32.lib' || '' }}

      - name: Install wasm-opt
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y binaryen

      - name: Build Web
        if: matrix.os == 'ubuntu-latest'
        run: dx build --profile beta

      - name: Optimize WASM
        if: matrix.os == 'ubuntu-latest'
        run: |
          wasm-opt -Oz target/wasm32-unknown-unknown/beta/Cowcord.wasm -o target/wasm32-unknown-unknown/beta/Cowcord-optimized.wasm
          mv target/wasm32-unknown-unknown/beta/Cowcord-optimized.wasm target/wasm32-unknown-unknown/beta/Cowcord.wasm

      - name: Deploy Web
        if: matrix.os == 'ubuntu-latest'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=target/dx/Cowcord/beta/web/public --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_BETA }}

      - name: Build Desktop
        if: matrix.os == 'windows-latest'
        run: dx bundle --platform desktop --profile beta

      - name: Create Pre-release
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.run_number }}-beta"
          name: "Beta Release ${{ github.run_number }}"
          prerelease: true
          files: dist/*.exe
          body: |
            - Commit: ${{ github.sha }}
            - Built on: ${{ github.event_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
