name: Deploy Beta

on:
  push:
    branches:
      - beta

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip_deploy')"
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.os == 'ubuntu-latest' && 'wasm32-unknown-unknown' || '' }}

      - uses: Swatinem/rust-cache@v2

      - name: Install Dioxus cli
        run: cargo install dioxus-cli

      # - name: Install wasm-opt
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y binaryen

      - name: Build web
        if: matrix.os == 'ubuntu-latest'
        run: dx build --profile beta && cp -r ./target/dx/Cowcord/debug/web/public ./dist

      # - name: Optimize wasm
      #   if: matrix.os == 'ubuntu-latest'
      #   run: wasm-opt dist/assets/dioxus/Cowcord_bg.wasm -o dist/assets/dioxus/Cowcord_bg.wasm -O4

      - name: Deploy web
        if: matrix.os == 'ubuntu-latest'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./dist
          clean: true
          token: ${{ secrets.ACCESS_TOKEN }}

      # - name: Build Desktop
      #   if: matrix.os == 'windows-latest'
      #   run: dx bundle --platform desktop --profile beta

      # - name: Create Pre-release
      #   if: matrix.os == 'windows-latest'
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: "v${{ github.run_number }}-beta"
      #     name: "Beta Release ${{ github.run_number }}"
      #     prerelease: true
      #     files: dist/*.exe
      #     body: |
      #       Beta releases are more likely to be buggy and possibly crash, however they get updates sooner and *should* run better

      #       - Commit: ${{ github.sha }}
      #       - Built on: ${{ github.event_name }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
