name: Deploy to Github pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and deploy
        uses: DioxusLabs/deploy-action@v1
        with:
          project-path: .
          platform: web
          release: true
          deploy: true
          deploy-branch: gh-pages
          deploy-folder: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
