name: I hate emojis

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check-emoji:
    runs-on: ubuntu-latest
    steps:
      - name: Check for emojis
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          COMMIT_MESSAGES=$(git log --pretty=%B --no-merges origin/${{ github.event.pull_request.base.ref }}..HEAD)

          EMOJI_PATTERN=$'\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251'

          if [[ "$PR_TITLE" =~ [$EMOJI_PATTERN] ]]; then
            exit 1
          fi

          while IFS= read -r line; do
            if [[ "$line" =~ [$EMOJI_PATTERN] ]]; then
              exit 1
            fi
          done <<< "$COMMIT_MESSAGES"
