name: Deploy Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip_deploy')"
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Install wasm-opt
        run: |
          sudo apt-get update
          sudo apt-get install -y binaryen

      - name: Build
        run: dx build --release

      - name: Optimize WASM
        run: |
          wasm-opt -Oz target/wasm32-unknown-unknown/release/Cowcord.wasm -o target/wasm32-unknown-unknown/release/Cowcord-optimized.wasm
          mv target/wasm32-unknown-unknown/release/Cowcord-optimized.wasm target/wasm32-unknown-unknown/release/Cowcord.wasm

      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=target/dx/Cowcord/release/web/public --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_RELEASE }}
